### ISSUE TITLE
Latest alembic migration should not drop classification index

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/telemetrics-backend#13]
https://github.com/clearlinux/telemetrics-backend/blob/d9d1dd2f90dc0d683da3fc3f54805f91b452d8aa/telemetryui/migrations/versions/466cf2f35d67_.py

This migration drops `classification_text_ind`, but the index does not exist.

**Comment by alexjch** [comment]
Reproducing bug, this is a side effect of the issue previously reported by Patrick.

**Comment by alexjch** [comment]
This is a duplicate of issue #12

**Comment by phmccarty** [comment]
@alexjch I filed a separate bug because there were two visible problems with the migration script. I suspect the root cause for each was different.

**Comment by phmccarty** [comment]
Resolved in #14
