### ISSUE TITLE
record details view: add board name, bios version, and cpu model name fields

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/telemetrics-backend#18]
Now that the Records table contains board_name, bios_version, and cpu_model, we should display these values in the Record Details view.

For records with record-format-version 2, we can display `N/A` for the fields.

**Comment by alexjch** [comment]
Created a pull request with this changes

**Comment by phmccarty** [comment]
PR link to #19

**Comment by phmccarty** [comment]
Merged #19
