### ISSUE TITLE
Plugin views not loading static directory

### ISSUE THREAD

**Issue by gabrielbriones** [clearlinux/telemetrics-backend#29]
When there are multiple plugin views, only the first view can load the static folder, the other ones will show the static files as not found 404.

**Comment by alexjch** [comment]
I added more details and consideration to documentation in this [PR](https://github.com/clearlinux/telemetrics-backend/pull/31), let me know if this solves the problem.

**Comment by alexjch** [comment]
Merged [PR](https://github.com/clearlinux/telemetrics-backend/pull/31) that fixes this issue.
