### ISSUE TITLE
Reprocessing crash records after updating blacklist generates "Internal Server Error"

### ISSUE THREAD

**Issue by reaganlo** [clearlinux/telemetrics-backend#46]
In the Crashes tab, check one of the blacklist of a guilty record and click "Apply". Then reprocess the crash records by clicking "Submit". Webpage generates "Internal Server Error".

telemetryui_uwsgi.log indicates TypeError: process_guilties() got an unexpected keyword argument 'klass'

**Comment by alexjch** [comment]
Closing this since this was fixed after updating ```deploy.sh``` to install specific tag. The reason this was occurring is that the uwsgi spooler component was not installed.
