### ISSUE TITLE
telemetryui: add 3-day population trend graph to Population view

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/telemetrics-backend#8]
Because the telemetry machine ID, as managed by the telemetrics-client daemon (telemd), rotates every 72 hours by default, it would be nice to add a new chart to the Population view that displays record counts over a 3-day window. Maybe replace the 7-day chart with this one?

**Comment by alexjch** [comment]
I added one chart for 3 day period.  We'll come back later to remove the 7 day?

**Comment by phmccarty** [comment]
@alexjch Yeah, let's leave the 7-day one for now and decide later whether to remove it.

**Comment by phmccarty** [comment]
PR link #20

**Comment by phmccarty** [comment]
Merged #20
